### ISSUE TITLE
Make script to retrieve articles from NU.nl

### ISSUE THREAD

**Issue by SnevelRetlaw** [Crazy4Topix/Topix#26]
Make use of Edge functions in SupaBase.
From there, you should make an API call to localhost/our server.
This API call executes the RSS2pythonScipt, which is in the other repository. This script collects and processes the data in the RSS feeds.
This data contains keywords. You should check if any of these keywords match with our available topixs. If there is one or more matches, save the news article in the table in Supabase with all relevant topics. If there is no match, discard the news article.

**Comment by Gulianrdgd** [comment]
For the python script, see RSS2ScriptPython but remove the chatgpt implementation
