### ISSUE TITLE
Convert podcast scripts into audio fragments using Elevenlabs

### ISSUE THREAD

**Issue by SnevelRetlaw** [Crazy4Topix/Topix#29]
Make a script that automatically triggers an API call to Elevenlabs if the podcast script of a news article becomes available.
The result should be stored on our own amazon server.

Use an Edgefunction from Supabase for this. Make sure that there are arguments for voice and article.

**Comment by stefanvi** [comment]
This may also be a possibility https://github.com/supabase-community/supabase-py
